/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ShoppingCheckoutSimulator;

/**
 *
 * @author rleiva
 */
public class ShoppingCartSimulator extends javax.swing.JFrame {

    /**
     * Creates new form ShoppingCartSimulator
     */
    
    //private int beefPounds;
    //private int chickenPounds;
    //private int fishPounds;
    //private int ricePounds;
    //private int beansPounds;
    //private int spaghettiPounds;
    
    public ShoppingCartSimulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_item = new javax.swing.JLabel();
        jLabelpricePerPound = new javax.swing.JLabel();
        jLabel_pounds = new javax.swing.JLabel();
        jLabel_beef = new javax.swing.JLabel();
        jLabel_chicken = new javax.swing.JLabel();
        jLabel_fish = new javax.swing.JLabel();
        jLabel_rice = new javax.swing.JLabel();
        jLabel_beans = new javax.swing.JLabel();
        jLabel_spaghetti = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton_calculateTotal = new javax.swing.JButton();
        jButton_cancel = new javax.swing.JButton();
        jButton_reset = new javax.swing.JButton();
        jButton_checkout = new javax.swing.JButton();
        jLabel_total = new javax.swing.JLabel();
        jTextField_chickenPounds = new javax.swing.JTextField();
        jTextField_beefPounds = new javax.swing.JTextField();
        jTextField_fishPounds = new javax.swing.JTextField();
        jTextField_ricePounds = new javax.swing.JTextField();
        jTextField_beansPounds = new javax.swing.JTextField();
        jTextField_spaghettiPounds = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_item.setText("Item");

        jLabelpricePerPound.setText("Price Per Pound");

        jLabel_pounds.setText("Pounds");

        jLabel_beef.setText("Beef");

        jLabel_chicken.setText("Chicken");

        jLabel_fish.setText("Fish");

        jLabel_rice.setText("Rice");

        jLabel_beans.setText("Beans");

        jLabel_spaghetti.setText("Spaghetti");

        jLabel1.setText("5");

        jLabel2.setText("4");

        jLabel3.setText("8");

        jLabel4.setText("2");

        jLabel5.setText("3");

        jLabel6.setText("4");

        jButton_calculateTotal.setText("Calculate Total");
        jButton_calculateTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calculateTotalActionPerformed(evt);
            }
        });

        jButton_cancel.setText("Cancel");

        jButton_reset.setText("Reset");

        jButton_checkout.setText("Checkout");

        jLabel_total.setText(" ");

        jTextField_chickenPounds.setText("0");

        jTextField_beefPounds.setText("0");

        jTextField_fishPounds.setText("0");

        jTextField_ricePounds.setText("0");

        jTextField_beansPounds.setText("0");

        jTextField_spaghettiPounds.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jButton_reset)
                .addGap(64, 64, 64)
                .addComponent(jButton_checkout)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_beef)
                            .addComponent(jLabel_item)
                            .addComponent(jLabel_chicken)
                            .addComponent(jLabel_fish)
                            .addComponent(jLabel_rice)
                            .addComponent(jLabel_beans)
                            .addComponent(jLabel_spaghetti))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelpricePerPound)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(141, 141, 141)
                                        .addComponent(jLabel_pounds)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField_beefPounds, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                            .addComponent(jTextField_chickenPounds)
                                            .addComponent(jTextField_fishPounds)
                                            .addComponent(jTextField_ricePounds)
                                            .addComponent(jTextField_beansPounds)
                                            .addComponent(jTextField_spaghettiPounds)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jButton_calculateTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_total)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_item)
                            .addComponent(jLabelpricePerPound)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel_pounds)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_beefPounds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_beef)
                                    .addComponent(jLabel1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_chicken)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_chickenPounds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_fish)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_fishPounds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_rice)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_ricePounds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel_beans)
                            .addComponent(jTextField_beansPounds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_spaghetti)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_spaghettiPounds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_calculateTotal)
                    .addComponent(jLabel_total))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_cancel)
                    .addComponent(jButton_reset)
                    .addComponent(jButton_checkout))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_calculateTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calculateTotalActionPerformed

        int beefPrice = Integer.parseInt(jTextField_beefPounds.getText()) * 5;
        int chickenPrice = Integer.parseInt(jTextField_chickenPounds.getText()) * 4;
        int fishPrice = Integer.parseInt(jTextField_fishPounds.getText()) * 8;
        int ricePrice = Integer.parseInt(jTextField_ricePounds.getText()) * 2;
        int beansPrice = Integer.parseInt(jTextField_beansPounds.getText()) * 3;
        int spaghettiPrice = Integer.parseInt(jTextField_spaghettiPounds.getText()) * 4;
        int total = beefPrice + chickenPrice + fishPrice + ricePrice + beansPrice + spaghettiPrice;
        
        jLabel_total.setText(Integer.toString(total));
    }//GEN-LAST:event_jButton_calculateTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShoppingCartSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShoppingCartSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShoppingCartSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShoppingCartSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShoppingCartSimulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_calculateTotal;
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_checkout;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_beans;
    private javax.swing.JLabel jLabel_beef;
    private javax.swing.JLabel jLabel_chicken;
    private javax.swing.JLabel jLabel_fish;
    private javax.swing.JLabel jLabel_item;
    private javax.swing.JLabel jLabel_pounds;
    private javax.swing.JLabel jLabel_rice;
    private javax.swing.JLabel jLabel_spaghetti;
    private javax.swing.JLabel jLabel_total;
    private javax.swing.JLabel jLabelpricePerPound;
    private javax.swing.JTextField jTextField_beansPounds;
    private javax.swing.JTextField jTextField_beefPounds;
    private javax.swing.JTextField jTextField_chickenPounds;
    private javax.swing.JTextField jTextField_fishPounds;
    private javax.swing.JTextField jTextField_ricePounds;
    private javax.swing.JTextField jTextField_spaghettiPounds;
    // End of variables declaration//GEN-END:variables
}
